### ISSUE TITLE
"Failed to associate device." in Sending Wi-Fi Credentials in ESP Rainmaker App. (MEGH-5828)

### ISSUE THREAD

**Issue by santoshurlam** [espressif/esp-rainmaker#322] opened 2024-07-25 12:44 UTC
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### Wi-Fi Connectivity Issue with RainMaker App 
When I'm running a example code of RMaker Switch, it was providing QR code and after scanning QR code through the ESP Rainmaker app after providing Wi-Fi credentials it is showing error in step 1 Sending Wi-Fi credentials: "Failed to associate device.".

1. I have tried with BLE and Softap provisioning but not worked.
2. I have tried with different Wi-Fi networks and also even by changing its security levels from WPA/WPA2 to open but not worked.
3.  I have tried asking chatgpt4.0 to modify the existing example code to get rid of those errors that I'm getting in Serial Monitor .
4.  I have changed all the settings which are suggested in the internet but not worked .
5. I have degraded my ide, board versions as suggested in internet but didn't worked.
6. Even I have changed the Wi-Fi settings in my mobile through developer options but, didn't worked.
![esp rmaker error](https://github.com/user-attachments/assets/79503bd0-1d2a-40bc-ba04-73d3e037d4ea)

The errors I got in serial monitor were ;
![Screenshot 2024-07-25 171154](https://github.com/user-attachments/assets/26acf50c-33e3-4c49-a07d-be142884d2ae)

I'm using ESP32-WROOM 32D with Arduino ide version 2.3.2 and esp32 board manager version 3.0.2 .
Anyone give me some suggestions on to get over with this issue.
These are the tools settings I'm using and some I altered the settings also but didn't worked.
![Screenshot 2024-07-25 181344](https://github.com/user-attachments/assets/f392f8ac-9156-4029-bcd1-d47693611bfb)

**Comment by shahpiyushv** [comment] 2024-07-25 13:03
Can you try by setting Partition Scheme as RainMaker, as mentioned in [this README ](https://github.com/espressif/arduino-esp32/blob/master/libraries/RainMaker/examples/README.md)?

**Comment by santoshurlam** [comment] 2024-07-25 14:25
> Can you try by setting Partition Scheme as RainMaker, as mentioned in [this README ](https://github.com/espressif/arduino-esp32/blob/master/libraries/RainMaker/examples/README.md)?

Yeah I've tried that also but didn't worked , it gave bootloop in serial monitor.

**Comment by santoshurlam** [comment] 2024-07-25 14:48
> @santoshurlam , serial monitor logs with the correct partition table?

I have used partition scheme : "RainMaker" but gave bootloop in serial monitor and then I've tried using "Huge APP" partition scheme atleast gave QR code but got the "Failed to associate device " issue in rainmaker app, as I've already mentioned above.

**Comment by shahpiyushv** [comment] 2024-07-25 16:03
@santoshurlam , yes you have mentioned in the comment above that "it gave bootloop in serial monitor ", but it is not clear what you mean here. Is your device rebooting continuously? It can happen in one of the 2 cases:
1. The bootloader did not find a valid firmware
2. The firmware loaded but crashed due to some reason.

Without any logs for this scenario, we cannot say what the issue is. If the firmware itself was faulty, even in the first case, you wouldn't see any logs. Change in partition table does not change the firmware.

**Comment by santoshurlam** [comment] 2024-07-25 16:58
> @santoshurlam , yes you have mentioned in the comment above that "it gave bootloop in serial monitor ", but it is not clear what you mean here. Is your device rebooting continuously? It can happen in one of the 2 cases:
> 
> 1. The bootloader did not find a valid firmware
> 2. The firmware loaded but crashed due to some reason.
> 
> Without any logs for this scenario, we cannot say what the issue is. If the firmware itself was faulty, even in the first case, you wouldn't see any logs. Change in partition table does not change the firmware.

 sorry for not properly specifiying the issue.
But now I've used partition scheme : "Rainmaker" and after compiling and uploading , I've got these in serial monitor ;
![Screenshot 2024-07-25 222306](https://github.com/user-attachments/assets/2432594b-735d-47b4-8fd2-c039f712863a)
Correct me if I'm wrong anywhere bcoz I'm kinda new to this.
And also the tools settings which I've used this time ;
![Screenshot 2024-07-25 222827](https://github.com/user-attachments/assets/847287e6-cf1a-4637-b2ab-ad4a08ac0e11)

**Comment by santoshurlam** [comment] 2024-07-25 18:49
> Seems the firmware is not flashed correctly on your device. After you change the partition table, please try enabling the "Erase All Flash Before Sketch Upload" option in the settings shown above and then recompile and re-flash.

Sadly , I've tried now but same thing happened again like above.

**Comment by shahpiyushv** [comment] 2024-07-30 11:16
"As above" could mean 2 different things. The original issue or the one after correcting the partition table. For the latter, you haven't shared any logs so can't say if bootloader itself hasn't loaded or if firmware hasn't loaded or if firmware has loaded but crashing continuously.

**Comment by AntonKozlenko1969** [comment] 2024-08-04 20:37
The same problem. How can I fix this to move on? 
platform 3.0.4
QR - ok
![Error](https://github.com/user-attachments/assets/13264f24-cd64-4fec-b308-26b10545be4f)

Led flashing on button
BLE normal

**Comment by shahpiyushv** [comment] 2024-08-05 04:41
@AntonKozlenko1969  In the original issue, the flash partition scheme was wrong, throwing nvs errors. When that was fixed, it was mentioned that the device keeps rebooting (but no logs were shared).

In your case, I see that you have shown that partition table is correct and QR code is printed. So not sure what you mean by "Same problem". Can you elaborate and share screenshots of phone app showing error and the corresponding serial terminal log ? Most of your log before the QR code is also hidden, so the info is incomplete.

**Comment by AntonKozlenko1969** [comment] 2024-08-21 08:27
Good afternoon.
After several unsuccessful attempts on the existing Arduino IDE
configuration, I solved the problem in a different way.
I have another computer on which a "clean" ARDUINO IDE 2.1.1 is installed
with the "ESP32 by Espressif" 2.0.5 platform.
And in this configuration everything worked !!!
Probably the problem occurs when the "ESP32 by Espressif" platform is
installed after the "Arduino ESP32 Boards" platform.
Even after removing the "Arduino ESP32 Boards" platform from Arduino IDE,
something remains in the system and the IDE takes the wrong libraries.

пн, 5 авг. 2024 г. в 07:41, Piyush Shah ***@***.***>:

**Comment by shahpiyushv** [comment] 2024-10-16 14:06
Closing this as the issue was eventually resolved.

**Closed by shahpiyushv** 2024-10-16 14:06 UTC

**Comment by vper87** [comment] 2025-01-31 19:23
> ### Answers checklist.
> * [x]  I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.[x]  I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.[x]  I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.
> 
> ### General issue report
> ### Wi-Fi Connectivity Issue with RainMaker App
> When I'm running a example code of RMaker Switch, it was providing QR code and after scanning QR code through the ESP Rainmaker app after providing Wi-Fi credentials it is showing error in step 1 Sending Wi-Fi credentials: "Failed to associate device.".
> 
> 1. I have tried with BLE and Softap provisioning but not worked.
> 2. I have tried with different Wi-Fi networks and also even by changing its security levels from WPA/WPA2 to open but not worked.
> 3. I have tried asking chatgpt4.0 to modify the existing example code to get rid of those errors that I'm getting in Serial Monitor .
> 4. I have changed all the settings which are suggested in the internet but not worked .
> 5. I have degraded my ide, board versions as suggested in internet but didn't worked.
> 6. Even I have changed the Wi-Fi settings in my mobile through developer options but, didn't worked.
>    ![esp rmaker error](https://github.com/user-attachments/assets/79503bd0-1d2a-40bc-ba04-73d3e037d4ea)
> 
> The errors I got in serial monitor were ; ![Screenshot 2024-07-25 171154](https://github.com/user-attachments/assets/26acf50c-33e3-4c49-a07d-be142884d2ae)
> 
> I'm using ESP32-WROOM 32D with Arduino ide version 2.3.2 and esp32 board manager version 3.0.2 . Anyone give me some suggestions on to get over with this issue. These are the tools settings I'm using and some I altered the settings also but didn't worked. ![Screenshot 2024-07-25 181344](https://github.com/user-attachments/assets/f392f8ac-9156-4029-bcd1-d47693611bfb)



> ### Answers checklist.
> * [x]  I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.[x]  I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.[x]  I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.
> 
> ### General issue report
> ### Wi-Fi Connectivity Issue with RainMaker App
> When I'm running a example code of RMaker Switch, it was providing QR code and after scanning QR code through the ESP Rainmaker app after providing Wi-Fi credentials it is showing error in step 1 Sending Wi-Fi credentials: "Failed to associate device.".
> 
> 1. I have tried with BLE and Softap provisioning but not worked.
> 2. I have tried with different Wi-Fi networks and also even by changing its security levels from WPA/WPA2 to open but not worked.
> 3. I have tried asking chatgpt4.0 to modify the existing example code to get rid of those errors that I'm getting in Serial Monitor .
> 4. I have changed all the settings which are suggested in the internet but not worked .
> 5. I have degraded my ide, board versions as suggested in internet but didn't worked.
> 6. Even I have changed the Wi-Fi settings in my mobile through developer options but, didn't worked.
>    ![esp rmaker error](https://github.com/user-attachments/assets/79503bd0-1d2a-40bc-ba04-73d3e037d4ea)
> 
> The errors I got in serial monitor were ; ![Screenshot 2024-07-25 171154](https://github.com/user-attachments/assets/26acf50c-33e3-4c49-a07d-be142884d2ae)
> 
> I'm using ESP32-WROOM 32D with Arduino ide version 2.3.2 and esp32 board manager version 3.0.2 . Anyone give me some suggestions on to get over with this issue. These are the tools settings I'm using and some I altered the settings also but didn't worked. ![Screenshot 2024-07-25 181344](https://github.com/user-attachments/assets/f392f8ac-9156-4029-bcd1-d47693611bfb)



> > Can you try by setting Partition Scheme as RainMaker, as mentioned in [this README ](https://github.com/espressif/arduino-esp32/blob/master/libraries/RainMaker/examples/README.md)?
> 
> Yeah I've tried that also but didn't worked , it gave bootloop in serial monitor.



> ### Answers checklist.
> * [x]  I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.[x]  I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.[x]  I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.
> 
> ### General issue report
> ### Wi-Fi Connectivity Issue with RainMaker App
> When I'm running a example code of RMaker Switch, it was providing QR code and after scanning QR code through the ESP Rainmaker app after providing Wi-Fi credentials it is showing error in step 1 Sending Wi-Fi credentials: "Failed to associate device.".
> 
> 1. I have tried with BLE and Softap provisioning but not worked.
> 2. I have tried with different Wi-Fi networks and also even by changing its security levels from WPA/WPA2 to open but not worked.
> 3. I have tried asking chatgpt4.0 to modify the existing example code to get rid of those errors that I'm getting in Serial Monitor .
> 4. I have changed all the settings which are suggested in the internet but not worked .
> 5. I have degraded my ide, board versions as suggested in internet but didn't worked.
> 6. Even I have changed the Wi-Fi settings in my mobile through developer options but, didn't worked.
>    ![esp rmaker error](https://github.com/user-attachments/assets/79503bd0-1d2a-40bc-ba04-73d3e037d4ea)
> 
> The errors I got in serial monitor were ; ![Screenshot 2024-07-25 171154](https://github.com/user-attachments/assets/26acf50c-33e3-4c49-a07d-be142884d2ae)
> 
> I'm using ESP32-WROOM 32D with Arduino ide version 2.3.2 and esp32 board manager version 3.0.2 . Anyone give me some suggestions on to get over with this issue. These are the tools settings I'm using and some I altered the settings also but didn't worked. ![Screenshot 2024-07-25 181344](https://github.com/user-attachments/assets/f392f8ac-9156-4029-bcd1-d47693611bfb)

Hey we're you able to solve this issue, even I've been trying to solving this an had several unsuccessful attempts...

**Comment by shahpiyushv** [comment] 2025-02-03 04:51
Seems you have flashed incorrect partition table. Please check out the first line in [this README](https://github.com/espressif/arduino-esp32/tree/master/libraries/RainMaker/examples#esp-rainmaker-examples) and choose one of the appropriate partition tables.
