### ISSUE TITLE
Buffer size 2048 not sufficient for node config (MEGH-2628)

### ISSUE THREAD

**Issue by ajarsco** [espressif/esp-rainmaker#88] opened 2021-07-25 18:32 UTC
I also encounter the same issue! How to solve this. Happened during adding multiple switches...
error:

⸮E (8799) esp_rmaker_node config: Buffer size 2048 not sufficient for Node Config.
E (8800) esp_rmaker_node_config: Could not get node configuration for reporting to cloud
E (8803) esp_rmaker_core: Report node config failed. E (8808) esp_rmaker_core: Aborting!!!

**Comment by shahpiyushv** [comment] 2021-07-27 17:10
Closing this issue since it is a duplicate of https://github.com/espressif/esp-rainmaker/issues/64

**Closed by shahpiyushv** 2021-07-27 17:10 UTC
